### ISSUE TITLE
Error: Invalid provider registry host

### ISSUE THREAD

**Issue by tekumara** [hashicorp/terraform-provider-hashicups-pf#16]
When following the README.md

```
❯ go build -o terraform-provider-hashicups

❯ make install 
go build -o terraform-provider-hashicups-pf
mkdir -p ~/.terraform.d/plugins/hashicorp.com/edu/hashicups-pf/0.3.2/darwin_amd64
mv terraform-provider-hashicups-pf ~/.terraform.d/plugins/hashicorp.com/edu/hashicups-pf/0.3.2/darwin_amd64

❯ cd examples

❯ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp.com/edu/hashicups-pf...

╷
│ Error: Invalid provider registry host
│ 
│ The host "hashicorp.com" given in in provider source address "hashicorp.com/edu/hashicups-pf" does not offer a Terraform provider registry.
╵
```

**Comment by independentid** [comment]
I have run into this. The current framework boilerplate is out of sync with the Hashicups tutorial. If you try to apply the tutorial main.go to avoid the above problem, tfsdk.Serve will not work (assume it is out of date).

It is not clear what the ServeOps{Address: "<value>"} should be when developing and testing locally (unpublished).

**Comment by bflad** [comment]
Hi folks 👋 The prior single Learn tutorial has been replaced with an [entire collection](https://learn.hashicorp.com/collections/terraform/providers-plugin-framework) now, which necessitated updating some of the tutorial contents. If you are still having issues with the latest tutorials and this code, please reach out. 👍
