### ISSUE TITLE
Actualize Provider interface path

### ISSUE THREAD

**Issue by Gordejj** [hashicorp/terraform-provider-hashicups-pf#22]
Hi there,

Please, actualize this [change](https://github.com/hashicorp/terraform-plugin-framework/commit/3b0c5196c2154404a0f725fce7a4cac5960eecbf) in [terraform-provider-hashicups-pf](https://github.com/hashicorp/terraform-provider-hashicups-pf) repo

**Comment by bflad** [comment]
Hi @Gordejj 👋 Thank you for raising this.

The single Learn tutorial has been replaced with an [entire collection](https://learn.hashicorp.com/collections/terraform/providers-plugin-framework) now. As part of those updates, this code update was addressed.

Thanks again!
