### ISSUE TITLE
This code repo and the related tutorial should conform to the https://github.com/hashicorp/terraform-provider-scaffolding-framework layout

### ISSUE THREAD

**Issue by spkane** [hashicorp/terraform-provider-hashicups-pf#45]
This code repo uses a slightly different layout then https://github.com/hashicorp/terraform-provider-scaffolding-framework.

In particular it does not put the provider, data sources, and resources under `./internal/provider`. This means that if you follow the tutorial to start up a custom provider, your layout will be different then what the scaffolding recommends.

**Comment by judithpatudith** [comment]
Good catch, thank you! We have a task to update the tutorial to include the scaffolding 🎉
